import type { Listing, PropertyRequest } from '@/lib/data'
import type {
  AccountStatus,
  AgentProfile,
  DealEvent,
  Message,
  Notification,
  Order,
  Lease,
  Review,
  Submission,
  ThreadRead,
} from '../types'
import {
  compact,
  isoString,
  nullable,
  type Row,
  type TableSpec,
} from './sql-repository'

export const listingTable: TableSpec<Listing> = {
  table: 'listings',
  columns: [
    'id',
    'name',
    'category',
    'zoning',
    'layout',
    'floor_area',
    'built_year',
    'nearest_station',
    'walk_minutes',
    'prefecture',
    'city',
    'image',
    'images',
    'summary',
    'deals',
    'sale_price',
    'rent_per_month',
    'deposit_months',
    'key_money_months',
    'lease_type',
    'purchase_option',
    'purchase_option_credit_rate',
    'purchase_option_credit_cap',
    'seller_name',
    'seller_kind',
    'seller_rating',
    'seller_reviews',
    'tags',
    'owner_user_id',
    'created_at',
    'updated_at',
    'moderation_status',
    'moderation_note',
    'moderated_at',
    'withdrawn_at',
  ],
  toRow: (listing) => [
    listing.id,
    listing.name,
    listing.category,
    listing.zoning,
    nullable(listing.layout),
    listing.floorArea,
    nullable(listing.builtYear),
    listing.nearestStation,
    listing.walkMinutes,
    listing.prefecture,
    listing.city,
    listing.image,
    nullable(listing.images),
    listing.summary,
    listing.deals,
    nullable(listing.salePrice),
    nullable(listing.rentPerMonth),
    nullable(listing.depositMonths),
    nullable(listing.keyMoneyMonths),
    nullable(listing.leaseType),
    nullable(listing.purchaseOption),
    nullable(listing.purchaseOptionCreditRate),
    nullable(listing.purchaseOptionCreditCap),
    listing.seller.name,
    listing.seller.kind,
    listing.seller.rating,
    listing.seller.reviews,
    listing.tags,
    nullable(listing.ownerUserId),
    nullable(listing.createdAt),
    nullable(listing.updatedAt),
    nullable(listing.moderationStatus),
    nullable(listing.moderationNote),
    nullable(listing.moderatedAt),
    nullable(listing.withdrawnAt),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      name: row.name as string,
      category: row.category as string,
      zoning: row.zoning as Listing['zoning'],
      layout: (row.layout as Listing['layout'] | null) ?? undefined,
      floorArea: row.floor_area as number,
      builtYear: (row.built_year as number | null) ?? undefined,
      nearestStation: row.nearest_station as string,
      walkMinutes: row.walk_minutes as number,
      prefecture: row.prefecture as string,
      city: row.city as string,
      image: row.image as string,
      images: (row.images as string[] | null) ?? undefined,
      summary: row.summary as string,
      deals: row.deals as Listing['deals'],
      salePrice: (row.sale_price as number | null) ?? undefined,
      rentPerMonth: (row.rent_per_month as number | null) ?? undefined,
      depositMonths: (row.deposit_months as number | null) ?? undefined,
      keyMoneyMonths: (row.key_money_months as number | null) ?? undefined,
      leaseType: (row.lease_type as Listing['leaseType'] | null) ?? undefined,
      purchaseOption: (row.purchase_option as boolean | null) ?? undefined,
      purchaseOptionCreditRate:
        (row.purchase_option_credit_rate as number | null) ?? undefined,
      purchaseOptionCreditCap:
        (row.purchase_option_credit_cap as number | null) ?? undefined,
      seller: {
        name: row.seller_name as string,
        kind: row.seller_kind as Listing['seller']['kind'],
        rating: row.seller_rating as number,
        reviews: row.seller_reviews as number,
      },
      tags: row.tags as string[],
      ownerUserId: (row.owner_user_id as string | null) ?? undefined,
      createdAt: isoString(row.created_at),
      updatedAt: isoString(row.updated_at),
      moderationStatus:
        (row.moderation_status as Listing['moderationStatus'] | null) ??
        undefined,
      moderationNote: (row.moderation_note as string | null) ?? undefined,
      moderatedAt: isoString(row.moderated_at),
      withdrawnAt: isoString(row.withdrawn_at),
    }),
}

export const propertyRequestTable: TableSpec<PropertyRequest> = {
  table: 'property_requests',
  columns: [
    'id',
    'title',
    'deal',
    'category',
    'layout',
    'prefecture',
    'city',
    'budget',
    'move_in_date',
    'status',
    'owner_user_id',
    'created_at',
    'updated_at',
    'moderation_status',
    'moderation_note',
    'moderated_at',
  ],
  toRow: (request) => [
    request.id,
    request.title,
    request.deal,
    request.category,
    nullable(request.layout),
    request.prefecture,
    request.city,
    request.budget,
    request.moveInDate,
    request.status,
    nullable(request.ownerUserId),
    nullable(request.createdAt),
    nullable(request.updatedAt),
    nullable(request.moderationStatus),
    nullable(request.moderationNote),
    nullable(request.moderatedAt),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      title: row.title as string,
      deal: row.deal as PropertyRequest['deal'],
      category: row.category as string,
      layout: (row.layout as PropertyRequest['layout'] | null) ?? undefined,
      prefecture: row.prefecture as string,
      city: row.city as string,
      budget: row.budget as number,
      moveInDate: row.move_in_date as string,
      status: row.status as PropertyRequest['status'],
      ownerUserId: (row.owner_user_id as string | null) ?? undefined,
      createdAt: isoString(row.created_at),
      updatedAt: isoString(row.updated_at),
      moderationStatus:
        (row.moderation_status as PropertyRequest['moderationStatus'] | null) ??
        undefined,
      moderationNote: (row.moderation_note as string | null) ?? undefined,
      moderatedAt: isoString(row.moderated_at),
    }),
}

export const submissionTable: TableSpec<Submission> = {
  table: 'submissions',
  columns: [
    'id',
    'kind',
    'target_id',
    'user_id',
    'received_at',
    'payload',
    'status',
  ],
  toRow: (submission) => [
    submission.id,
    submission.kind,
    nullable(submission.targetId),
    nullable(submission.userId),
    submission.receivedAt,
    JSON.stringify(submission.payload),
    nullable(submission.status),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      kind: row.kind as Submission['kind'],
      targetId: (row.target_id as string | null) ?? undefined,
      userId: (row.user_id as string | null) ?? undefined,
      receivedAt: isoString(row.received_at) as string,
      payload: row.payload as Record<string, unknown>,
      status: (row.status as Submission['status'] | null) ?? undefined,
    }),
}

export const messageTable: TableSpec<Message> = {
  table: 'messages',
  columns: ['id', 'thread_id', 'sender_user_id', 'body', 'created_at'],
  toRow: (message) => [
    message.id,
    message.threadId,
    message.senderUserId,
    message.body,
    message.createdAt,
  ],
  fromRow: (row: Row) => ({
    id: row.id as string,
    threadId: row.thread_id as string,
    senderUserId: row.sender_user_id as string,
    body: row.body as string,
    createdAt: isoString(row.created_at) as string,
  }),
}

export const leaseTable: TableSpec<Lease> = {
  table: 'leases',
  columns: [
    'id',
    'listing_id',
    'tenant_user_id',
    'start_date',
    'end_date',
    'months',
    'rent_per_month',
    'rent_total',
    'deposit',
    'key_money',
    'initial_cost',
    'sale_price',
    'credit_rate',
    'credit_cap',
    'status',
    'purchase_price',
    'created_at',
    'updated_at',
  ],
  toRow: (lease) => [
    lease.id,
    lease.listingId,
    lease.tenantUserId,
    lease.startDate,
    lease.endDate,
    lease.months,
    lease.rentPerMonth,
    lease.rentTotal,
    lease.deposit,
    lease.keyMoney,
    lease.initialCost,
    nullable(lease.salePrice),
    nullable(lease.creditRate),
    nullable(lease.creditCap),
    lease.status,
    nullable(lease.purchasePrice),
    lease.createdAt,
    lease.updatedAt,
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      listingId: row.listing_id as string,
      tenantUserId: row.tenant_user_id as string,
      startDate: row.start_date as string,
      endDate: row.end_date as string,
      months: row.months as number,
      rentPerMonth: row.rent_per_month as number,
      rentTotal: row.rent_total as number,
      deposit: row.deposit as number,
      keyMoney: row.key_money as number,
      initialCost: row.initial_cost as number,
      salePrice: (row.sale_price as number | null) ?? undefined,
      creditRate: (row.credit_rate as number | null) ?? undefined,
      creditCap: (row.credit_cap as number | null) ?? undefined,
      status: row.status as Lease['status'],
      purchasePrice: (row.purchase_price as number | null) ?? undefined,
      createdAt: isoString(row.created_at) as string,
      updatedAt: isoString(row.updated_at) as string,
    }),
}

export const accountStatusTable: TableSpec<AccountStatus> = {
  table: 'account_statuses',
  columns: ['id', 'status', 'note', 'updated_at'],
  toRow: (row) => [row.id, row.status, nullable(row.note), row.updatedAt],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      status: row.status as AccountStatus['status'],
      note: (row.note as string | null) ?? undefined,
      updatedAt: isoString(row.updated_at) as string,
    }),
}

export const notificationTable: TableSpec<Notification> = {
  table: 'notifications',
  columns: [
    'id',
    'user_id',
    'kind',
    'title',
    'body',
    'href',
    'created_at',
    'read_at',
  ],
  toRow: (notification) => [
    notification.id,
    notification.userId,
    notification.kind,
    notification.title,
    nullable(notification.body),
    notification.href,
    notification.createdAt,
    nullable(notification.readAt),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      userId: row.user_id as string,
      kind: row.kind as Notification['kind'],
      title: row.title as string,
      body: (row.body as string | null) ?? undefined,
      href: row.href as string,
      createdAt: isoString(row.created_at) as string,
      readAt: isoString(row.read_at),
    }),
}

export const reviewTable: TableSpec<Review> = {
  table: 'reviews',
  columns: [
    'id',
    'listing_id',
    'seller_user_id',
    'reviewer_user_id',
    'source_kind',
    'source_id',
    'rating',
    'comment',
    'created_at',
  ],
  toRow: (review) => [
    review.id,
    review.listingId,
    review.sellerUserId,
    review.reviewerUserId,
    review.sourceKind,
    review.sourceId,
    review.rating,
    nullable(review.comment),
    review.createdAt,
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      listingId: row.listing_id as string,
      sellerUserId: row.seller_user_id as string,
      reviewerUserId: row.reviewer_user_id as string,
      sourceKind: row.source_kind as Review['sourceKind'],
      sourceId: row.source_id as string,
      rating: row.rating as number,
      comment: (row.comment as string | null) ?? undefined,
      createdAt: isoString(row.created_at) as string,
    }),
}

export const threadReadTable: TableSpec<ThreadRead> = {
  table: 'thread_reads',
  columns: ['id', 'thread_id', 'user_id', 'read_at'],
  toRow: (read) => [read.id, read.threadId, read.userId, read.readAt],
  fromRow: (row: Row) => ({
    id: row.id as string,
    threadId: row.thread_id as string,
    userId: row.user_id as string,
    readAt: isoString(row.read_at) as string,
  }),
}

export const agentProfileTable: TableSpec<AgentProfile> = {
  table: 'agent_profiles',
  columns: [
    'id',
    'name',
    'kind',
    'prefecture',
    'handled_categories',
    'service_areas',
    'note',
    'created_at',
    'updated_at',
  ],
  toRow: (profile) => [
    profile.id,
    profile.name,
    profile.kind,
    profile.prefecture,
    profile.handledCategories,
    profile.serviceAreas,
    nullable(profile.note),
    profile.createdAt,
    profile.updatedAt,
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      name: row.name as string,
      kind: row.kind as AgentProfile['kind'],
      prefecture: row.prefecture as string,
      handledCategories: row.handled_categories as string[],
      serviceAreas: row.service_areas as string[],
      note: (row.note as string | null) ?? undefined,
      createdAt: isoString(row.created_at) as string,
      updatedAt: isoString(row.updated_at) as string,
    }),
}

export const orderTable: TableSpec<Order> = {
  table: 'orders',
  columns: [
    'id',
    'listing_id',
    'buyer_user_id',
    'seller_user_id',
    'price',
    'status',
    'message',
    'source_lease_id',
    'created_at',
    'updated_at',
  ],
  toRow: (order) => [
    order.id,
    order.listingId,
    order.buyerUserId,
    order.sellerUserId,
    order.price,
    order.status,
    nullable(order.message),
    nullable(order.sourceLeaseId),
    order.createdAt,
    order.updatedAt,
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      listingId: row.listing_id as string,
      buyerUserId: row.buyer_user_id as string,
      sellerUserId: row.seller_user_id as string,
      price: row.price as number,
      status: row.status as Order['status'],
      message: (row.message as string | null) ?? undefined,
      sourceLeaseId: (row.source_lease_id as string | null) ?? undefined,
      createdAt: isoString(row.created_at) as string,
      updatedAt: isoString(row.updated_at) as string,
    }),
}

export const dealEventTable: TableSpec<DealEvent> = {
  table: 'deal_events',
  columns: [
    'id',
    'deal_kind',
    'deal_id',
    'actor_user_id',
    'status',
    'note',
    'created_at',
  ],
  toRow: (event) => [
    event.id,
    event.dealKind,
    event.dealId,
    nullable(event.actorUserId),
    event.status,
    nullable(event.note),
    event.createdAt,
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      dealKind: row.deal_kind as DealEvent['dealKind'],
      dealId: row.deal_id as string,
      actorUserId: (row.actor_user_id as string | null) ?? undefined,
      status: row.status as string,
      note: (row.note as string | null) ?? undefined,
      createdAt: isoString(row.created_at) as string,
    }),
}
