import 'server-only'

import type { Listing, PropertyRequest } from '@/lib/data'
import { generateListings } from './generated-listings'

const curatedListings: Listing[] = [
  {
    id: 'apt-001',
    name: 'シティタワー 世田谷区 3LDK',
    category: 'マンション',
    zoning: '第一種住居地域',
    layout: '3LDK',
    floorArea: 74.2,
    builtYear: 2019,
    nearestStation: '小田急線 経堂駅',
    walkMinutes: 6,
    prefecture: '東京都',
    city: '世田谷区',
    image: '/properties/apartment.webp',
    summary:
      '南向き角住戸の3LDK。管理体制がよく、共用部も清潔です。まず借りて住み心地を確かめてから購入に切り替えられます。',
    deals: ['sale', 'rent'],
    salePrice: 88_000_000,
    rentPerMonth: 268_000,
    depositMonths: 2,
    keyMoneyMonths: 1,
    leaseType: '普通借家',
    purchaseOption: true,
    purchaseOptionCreditRate: 50,
    purchaseOptionCreditCap: 5_000_000,
    seller: {
      name: '出品者デモ',
      kind: '宅建業者',
      rating: 4.8,
      reviews: 34,
    },
    tags: ['オートロック', '南向き', '角部屋'],
    ownerUserId: 'demo-seller',
  },
  {
    id: 'hse-002',
    name: 'ガレージ付戸建 横浜市港北区 4LDK以上',
    category: '戸建',
    zoning: '第一種低層住居専用地域',
    layout: '4LDK以上',
    floorArea: 118.6,
    builtYear: 2015,
    nearestStation: '東急東横線 綱島駅',
    walkMinutes: 11,
    prefecture: '神奈川県',
    city: '横浜市港北区',
    image: '/properties/house.webp',
    summary:
      'ビルトインガレージ付き。外壁と屋根は塗装済みで、点検記録をそのままお渡しします。定期借家での貸し出しにも対応します。',
    deals: ['sale', 'rent'],
    salePrice: 62_800_000,
    rentPerMonth: 235_000,
    depositMonths: 2,
    keyMoneyMonths: 0,
    leaseType: '定期借家',
    purchaseOption: true,
    purchaseOptionCreditRate: 50,
    purchaseOptionCreditCap: 6_000_000,
    seller: { name: '出品者デモ', kind: '宅建業者', rating: 4.6, reviews: 58 },
    tags: ['駐車場2台', '耐震基準適合', '南向き'],
    ownerUserId: 'demo-seller',
  },
  {
    id: 'apt-003',
    name: 'ルミエール 大阪市北区 1LDK',
    category: 'マンション',
    zoning: '商業地域',
    layout: '1LDK',
    floorArea: 42.8,
    builtYear: 2012,
    nearestStation: 'JR大阪環状線 天満駅',
    walkMinutes: 4,
    prefecture: '大阪府',
    city: '大阪市北区',
    image: '/properties/apartment.webp',
    summary:
      '単身・二人暮らし向けの1LDK。駅まで平坦で、周辺に商店街と病院があります。',
    deals: ['rent'],
    rentPerMonth: 132_000,
    depositMonths: 1,
    keyMoneyMonths: 1,
    leaseType: '普通借家',
    purchaseOption: false,
    seller: { name: '出品者デモ', kind: '宅建業者', rating: 4.4, reviews: 41 },
    tags: ['宅配ボックス', 'ペット可'],
    ownerUserId: 'demo-seller',
  },
  {
    id: 'lnd-004',
    name: '建築条件なし売地 さいたま市浦和区',
    category: '土地',
    zoning: '第一種低層住居専用地域',
    floorArea: 152.4,
    nearestStation: 'JR京浜東北線 浦和駅',
    walkMinutes: 14,
    prefecture: '埼玉県',
    city: 'さいたま市浦和区',
    image: '/properties/land.webp',
    summary:
      '測量済みの整形地で、境界も明示できます。建築条件はありません。上下水道は前面道路に敷設済みです。',
    deals: ['sale'],
    salePrice: 43_800_000,
    purchaseOption: false,
    seller: { name: '山田地所', kind: '法人', rating: 4.7, reviews: 63 },
    tags: ['整形地', '建築条件なし', '上水道引込済'],
    ownerUserId: 'yamada-jisho',
  },
  {
    id: 'cml-005',
    name: '1階路面店舗 福岡市中央区',
    category: '事業用',
    zoning: '近隣商業地域',
    layout: '1R',
    floorArea: 66.0,
    builtYear: 2008,
    nearestStation: '地下鉄空港線 赤坂駅',
    walkMinutes: 3,
    prefecture: '福岡県',
    city: '福岡市中央区',
    image: '/properties/shop.webp',
    summary:
      '視認性の高い路面区画です。内装は居抜きのままお引き渡しできます。用途のご相談は早めにお願いします。',
    deals: ['rent'],
    rentPerMonth: 385_000,
    depositMonths: 6,
    keyMoneyMonths: 2,
    leaseType: '定期借家',
    purchaseOption: false,
    seller: {
      name: 'スカイリアルティ',
      kind: '法人',
      rating: 4.5,
      reviews: 27,
    },
    tags: ['居抜き', '前面道路広い'],
    ownerUserId: 'sky-realty',
  },
  {
    id: 'apt-006',
    name: 'パークサイドレジデンス 名古屋市千種区 2LDK',
    category: 'マンション',
    zoning: '第一種中高層住居専用地域',
    layout: '2LDK',
    floorArea: 58.3,
    builtYear: 2004,
    nearestStation: '地下鉄東山線 今池駅',
    walkMinutes: 8,
    prefecture: '愛知県',
    city: '名古屋市千種区',
    image: '/properties/apartment.webp',
    summary:
      '室内はフルリノベーション済み。設備の保証書一式をお渡しします。管理費・修繕積立金の履歴も開示できます。',
    deals: ['sale', 'rent'],
    salePrice: 36_500_000,
    rentPerMonth: 148_000,
    depositMonths: 1,
    keyMoneyMonths: 1,
    leaseType: '普通借家',
    purchaseOption: true,
    purchaseOptionCreditRate: 40,
    purchaseOptionCreditCap: 3_000_000,
    seller: { name: '中村不動産', kind: '宅建業者', rating: 4.8, reviews: 34 },
    tags: ['リノベーション済', 'オートロック'],
    ownerUserId: 'nakamura-estate',
  },
]

export const listings: Listing[] = [
  ...curatedListings,
  ...generateListings(42, curatedListings.length + 1),
]

export const propertyRequests: PropertyRequest[] = [
  {
    id: 'pr-01',
    title: '保育園に通える2LDKを探しています',
    deal: 'rent',
    category: 'マンション',
    layout: '2LDK',
    prefecture: '東京都',
    city: '世田谷区',
    budget: 220_000,
    moveInDate: '2026-11-01',
    status: '募集中',
    ownerUserId: 'demo-seller',
  },
  {
    id: 'pr-02',
    title: '駐車場2台の戸建を購入したい',
    deal: 'sale',
    category: '戸建',
    layout: '4LDK以上',
    prefecture: '神奈川県',
    city: '横浜市港北区',
    budget: 68_000_000,
    moveInDate: '2027-03-01',
    status: '募集中',
    ownerUserId: 'demo-seller',
  },
  {
    id: 'pr-03',
    title: '自宅兼アトリエにできる戸建の賃貸',
    deal: 'rent',
    category: '戸建',
    layout: '3LDK',
    prefecture: '京都府',
    city: '京都市中京区',
    budget: 195_000,
    moveInDate: '2026-12-15',
    status: '調整中',
    ownerUserId: 'tamura',
  },
  {
    id: 'pr-04',
    title: '建築条件なしの整形地を探しています',
    deal: 'sale',
    category: '土地',
    prefecture: '埼玉県',
    city: 'さいたま市浦和区',
    budget: 48_000_000,
    moveInDate: '2027-06-01',
    status: '募集中',
    ownerUserId: 'kobayashi-kanri',
  },
  {
    id: 'pr-05',
    title: '路面の店舗区画（飲食可）を借りたい',
    deal: 'rent',
    category: '事業用',
    layout: '1R',
    prefecture: '福岡県',
    city: '福岡市中央区',
    budget: 420_000,
    moveInDate: '2026-11-20',
    status: '募集中',
    ownerUserId: 'sky-realty',
  },
  {
    id: 'pr-06',
    title: '単身用1Kを駅徒歩10分以内で',
    deal: 'rent',
    category: 'マンション',
    layout: '1K',
    prefecture: '大阪府',
    city: '大阪市北区',
    budget: 98_000,
    moveInDate: '2026-10-25',
    status: '募集中',
    ownerUserId: 'takahashi',
  },
  {
    id: 'pr-07',
    title: '二世帯で住める広めの戸建を購入したい',
    deal: 'sale',
    category: '戸建',
    layout: '4LDK以上',
    prefecture: '愛知県',
    city: '名古屋市千種区',
    budget: 75_000_000,
    moveInDate: '2027-04-01',
    status: '調整中',
    ownerUserId: 'yamada-jisho',
  },
  {
    id: 'pr-08',
    title: '倉庫として使える事業用物件を購入',
    deal: 'sale',
    category: '事業用',
    prefecture: '静岡県',
    city: '静岡市葵区',
    budget: 120_000_000,
    moveInDate: '2027-01-10',
    status: '募集中',
    ownerUserId: 'midori-kanri',
  },
  {
    id: 'pr-09',
    title: 'ペット可の1LDKに住み替えたい',
    deal: 'rent',
    category: 'マンション',
    layout: '1LDK',
    prefecture: '兵庫県',
    city: '神戸市東灘区',
    budget: 145_000,
    moveInDate: '2026-12-01',
    status: '募集中',
    ownerUserId: 'watanabe',
  },
  {
    id: 'pr-10',
    title: '資材置き場に使える土地を借りたい',
    deal: 'rent',
    category: '土地',
    prefecture: '長野県',
    city: '長野市',
    budget: 85_000,
    moveInDate: '2026-11-05',
    status: '募集中',
    ownerUserId: 'sato-jutaku',
  },
]
