import 'server-only'

import type { Listing, TransportJob } from '@/lib/data'
import { generateListings } from './generated-listings'

const curatedListings = generateListings(6, 1).map((listing, index) => ({
  ...listing,
  ownerUserId: [
    'demo-seller',
    'demo-seller',
    'tamura',
    'kobayashi-engei',
    'sky-agri',
    'tokachi-agri',
  ][index],
  id: ['trc-001', 'cmb-002', 'rpl-003', 'til-004', 'drn-005', 'trc-006'][index],
}))

export const listings: Listing[] = [
  ...curatedListings,
  ...generateListings(42, 7),
]

export const transportJobs: TransportJob[] = [
  {
    id: 'tj-01',
    item: 'ふたり暮らしの引越し',
    from: '秋田県 大仙市',
    to: '山形県 天童市',
    distanceKm: 120,
    weight: '2tトラック1台分',
    desiredDate: '9/28 午前',
    reward: 38_000,
    status: '募集中',
    ownerUserId: 'demo-seller',
  },
  {
    id: 'tj-02',
    item: '単身引越し・家具家電一式',
    from: '新潟県 長岡市',
    to: '新潟県 上越市',
    distanceKm: 75,
    weight: '単身・家具家電あり',
    desiredDate: '10/3 終日',
    reward: 22_000,
    status: '募集中',
    ownerUserId: 'demo-seller',
  },
  {
    id: 'tj-03',
    item: '新居への家具配送',
    from: '富山県 砺波市',
    to: '石川県 白山市',
    distanceKm: 55,
    weight: '家具5点',
    desiredDate: '10/6 午後',
    reward: 15_000,
    status: '調整中',
    ownerUserId: 'tamura',
  },
  {
    id: 'tj-04',
    item: '段ボールとデスクの配送',
    from: '長野県 松本市',
    to: '長野県 諏訪市',
    distanceKm: 40,
    weight: '段ボール10箱・デスク',
    desiredDate: '相談',
    reward: 6_000,
    status: '募集中',
    ownerUserId: 'kobayashi-engei',
  },
  {
    id: 'tj-05',
    item: '家族の引越し・3LDK',
    from: '北海道 帯広市',
    to: '北海道 旭川市',
    distanceKm: 180,
    weight: '4tトラック1台分',
    desiredDate: '10/12 午前',
    reward: 52_000,
    status: '募集中',
    ownerUserId: 'tokachi-agri',
  },
  {
    id: 'tj-06',
    item: '家電3点の配送',
    from: '福岡県 筑後市',
    to: '佐賀県 武雄市',
    distanceKm: 45,
    weight: '家電3点',
    desiredDate: '10/9 午後',
    reward: 8_000,
    status: '募集中',
    ownerUserId: 'sky-agri',
  },
  {
    id: 'tj-07',
    item: '住み替えに伴う引越し',
    from: '滋賀県 長浜市',
    to: '兵庫県 丹波篠山市',
    distanceKm: 110,
    weight: '2tトラック1台分',
    desiredDate: '10/15 終日',
    reward: 30_000,
    status: '調整中',
    ownerUserId: 'yamada-nosan',
  },
  {
    id: 'tj-08',
    item: 'ベッド・ソファの配送',
    from: '宮城県 登米市',
    to: '岩手県 花巻市',
    distanceKm: 95,
    weight: '大型家具2点',
    desiredDate: '相談',
    reward: 24_000,
    status: '募集中',
    ownerUserId: 'ito-farm',
  },
  {
    id: 'tj-09',
    item: '冷蔵庫・洗濯機の配送',
    from: '静岡県 掛川市',
    to: '愛知県 豊橋市',
    distanceKm: 70,
    weight: '家電2点',
    desiredDate: '10/20 午前',
    reward: 9_000,
    status: '募集中',
    ownerUserId: 'nakamura-farm',
  },
  {
    id: 'tj-10',
    item: '単身引越し・1LDK',
    from: '岡山県 真庭市',
    to: '広島県 東広島市',
    distanceKm: 130,
    weight: '単身・段ボール20箱',
    desiredDate: '10/25 終日',
    reward: 36_000,
    status: '募集中',
    ownerUserId: 'takahashi',
  },
]
