import 'server-only'

import { orderStatusLabels, type Listing, type PropertyRequest } from '@/lib/data'
import {
  calculateInitialCost,
  countLeaseMonths,
  leaseStatusLabels,
} from '@/lib/lease'
import type {
  AccountStatus,
  AgentProfile,
  DealEvent,
  DealKind,
  Message,
  Notification,
  Order,
  Lease,
  Review,
  Submission,
  ThreadRead,
} from './store/types'

/**
 * What the marketplace looks like after a few months of use: purchases,
 * leases, threads, hauls, and reviews between the demo accounts and the
 * personas. Loaded on top of the sample listings unless `DEMO_ACTIVITY=off`.
 */
export type DemoActivity = {
  listings: Listing[]
  propertyRequests: PropertyRequest[]
  submissions: Submission[]
  messages: Message[]
  leases: Lease[]
  orders: Order[]
  reviews: Review[]
  agentProfiles: AgentProfile[]
  notifications: Notification[]
  threadReads: ThreadRead[]
  accountStatuses: AccountStatus[]
  dealEvents: DealEvent[]
}

/** `at('09-13 10:30')` → ISO timestamp in 2026, JST. */
function at(stamp: string): string {
  const [date, time] = stamp.split(' ')
  return new Date(`2026-${date}T${time}:00+09:00`).toISOString()
}

const apartmentImage = '/properties/apartment.svg'

const listings: Listing[] = [
  {
    id: 'apt-101',
    name: 'アーバンビュー 世田谷区 2LDK',
    category: 'マンション',
    zoning: '第一種住居地域',
    layout: '2LDK',
    floorArea: 61.5,
    builtYear: 2021,
    nearestStation: '小田急線 経堂駅',
    walkMinutes: 5,
    prefecture: '東京都',
    city: '世田谷区',
    image: apartmentImage,
    summary:
      '駅から平坦な道で5分。まず借りて住み心地を確かめてから購入に切り替えられます。',
    deals: ['sale', 'rent'],
    salePrice: 64_800_000,
    rentPerMonth: 218_000,
    depositMonths: 2,
    keyMoneyMonths: 1,
    leaseType: '普通借家',
    purchaseOption: true,
    purchaseOptionCreditRate: 50,
    purchaseOptionCreditCap: 2_500_000,
    seller: { name: '出品者デモ', kind: '宅建業者', rating: 4.8, reviews: 34 },
    tags: ['オートロック', '南向き'],
    ownerUserId: 'demo-seller',
    createdAt: at('09-13 09:10'),
    updatedAt: at('09-13 09:10'),
    moderationStatus: 'pending',
  },
  {
    id: 'hse-102',
    name: '南向き中古戸建 仙台市青葉区 3LDK',
    category: '戸建',
    zoning: '第一種低層住居専用地域',
    layout: '3LDK',
    floorArea: 96.2,
    builtYear: 2015,
    nearestStation: 'JR仙山線 北仙台駅',
    walkMinutes: 12,
    prefecture: '宮城県',
    city: '仙台市青葉区',
    image: '/properties/house.svg',
    summary: '転勤に伴い手放します。引き渡しは年内を希望しています。',
    deals: ['sale'],
    salePrice: 38_200_000,
    purchaseOption: false,
    seller: { name: '山田地所', kind: '法人', rating: 4.7, reviews: 63 },
    tags: ['駐車場2台', 'リフォーム済'],
    ownerUserId: 'yamada-jisho',
    createdAt: at('09-12 18:40'),
    updatedAt: at('09-12 18:40'),
    moderationStatus: 'pending',
  },
  {
    id: 'apt-103',
    name: 'ルミエール 八王子市 1K',
    category: 'マンション',
    zoning: '近隣商業地域',
    layout: '1K',
    floorArea: 26.4,
    builtYear: 2020,
    nearestStation: 'JR中央線 八王子駅',
    walkMinutes: 7,
    prefecture: '東京都',
    city: '八王子市',
    image: apartmentImage,
    summary: '運営が検証用に掲載している単身向けの1K。短期の賃貸向け。',
    deals: ['rent'],
    rentPerMonth: 68_000,
    depositMonths: 1,
    keyMoneyMonths: 0,
    leaseType: '定期借家',
    purchaseOption: false,
    seller: { name: '運営デモ', kind: '法人', rating: 0, reviews: 0 },
    tags: ['宅配ボックス', '角部屋'],
    ownerUserId: 'demo-admin',
    createdAt: at('08-30 11:00'),
    updatedAt: at('08-30 11:20'),
    moderationStatus: 'approved',
    moderatedAt: at('08-30 11:20'),
  },
  {
    id: 'lnd-104',
    name: '角地の売地 世田谷区',
    category: '土地',
    zoning: '第一種低層住居専用地域',
    floorArea: 108.7,
    nearestStation: '小田急線 経堂駅',
    walkMinutes: 15,
    prefecture: '東京都',
    city: '世田谷区',
    image: '/properties/land.svg',
    summary: '相続した土地です。測量済みで境界も明示できます。',
    deals: ['sale'],
    salePrice: 52_000_000,
    purchaseOption: false,
    seller: { name: '出品者デモ', kind: '宅建業者', rating: 4.8, reviews: 34 },
    tags: ['角地', '整形地'],
    ownerUserId: 'demo-seller',
    createdAt: at('07-20 09:00'),
    updatedAt: at('08-12 16:00'),
    moderationStatus: 'approved',
    moderatedAt: at('07-20 10:00'),
    withdrawnAt: at('08-12 16:00'),
  },
  {
    id: 'hse-105',
    name: '庭付き一戸建て 南魚沼市 4LDK以上',
    category: '戸建',
    zoning: '第一種住居地域',
    layout: '4LDK以上',
    floorArea: 132.0,
    builtYear: 2009,
    nearestStation: 'JR上越線 六日町駅',
    walkMinutes: 18,
    prefecture: '新潟県',
    city: '南魚沼市',
    image: '/properties/house.svg',
    summary: '住み替えのため売却します。庭は家庭菜園にも使えます。',
    deals: ['sale'],
    salePrice: 21_500_000,
    purchaseOption: false,
    seller: {
      name: '中村不動産',
      kind: '宅建業者',
      rating: 4.8,
      reviews: 34,
    },
    tags: ['庭あり', '駐車場2台'],
    ownerUserId: 'nakamura-estate',
    createdAt: at('06-05 08:30'),
    updatedAt: at('07-02 12:00'),
    moderationStatus: 'approved',
    moderatedAt: at('06-05 09:00'),
    withdrawnAt: at('07-02 12:00'),
  },
  {
    id: 'cml-106',
    name: '事務所区画 横浜市港北区',
    category: '事業用',
    zoning: '商業地域',
    layout: '1R',
    floorArea: 84.5,
    builtYear: 2012,
    nearestStation: '東急東横線 綱島駅',
    walkMinutes: 4,
    prefecture: '神奈川県',
    city: '横浜市港北区',
    image: '/properties/commercial.svg',
    summary: '事務所として貸し出し中の区画です。用途のご相談は早めにお願いします。',
    deals: ['rent'],
    rentPerMonth: 264_000,
    depositMonths: 6,
    keyMoneyMonths: 1,
    leaseType: '定期借家',
    purchaseOption: false,
    seller: { name: '出品者デモ', kind: '宅建業者', rating: 4.8, reviews: 34 },
    tags: ['エレベーターあり', '24時間利用可'],
    ownerUserId: 'demo-seller',
    createdAt: at('08-01 10:00'),
    updatedAt: at('08-01 10:30'),
    moderationStatus: 'approved',
    moderatedAt: at('08-01 10:30'),
  },
]

const propertyRequests: PropertyRequest[] = [
  {
    id: 'pr-101',
    title: '通勤1時間以内の3LDKを購入したい',
    deal: 'sale',
    category: 'マンション',
    layout: '3LDK',
    prefecture: '東京都',
    city: '世田谷区',
    budget: 82_000_000,
    moveInDate: '2027-03-01',
    status: '紹介中',
    ownerUserId: 'demo-seller',
    createdAt: at('09-08 09:00'),
    updatedAt: at('09-13 08:05'),
    moderationStatus: 'approved',
    moderatedAt: at('09-08 09:30'),
  },
  {
    id: 'pr-102',
    title: '家族向けの戸建を借りたい',
    deal: 'rent',
    category: '戸建',
    layout: '4LDK以上',
    prefecture: '長野県',
    city: '長野市',
    budget: 165_000,
    moveInDate: '2026-12-01',
    status: '調整中',
    ownerUserId: 'ito-estate',
    createdAt: at('09-05 14:00'),
    updatedAt: at('09-11 17:30'),
    moderationStatus: 'approved',
    moderatedAt: at('09-05 14:20'),
  },
  {
    id: 'pr-103',
    title: '事務所として使える区画を探しています',
    deal: 'rent',
    category: '事業用',
    layout: '1R',
    prefecture: '埼玉県',
    city: 'さいたま市浦和区',
    budget: 240_000,
    moveInDate: '2026-11-10',
    status: '募集中',
    ownerUserId: 'kato',
    createdAt: at('09-13 07:45'),
    updatedAt: at('09-13 07:45'),
    moderationStatus: 'pending',
  },
  {
    id: 'pr-104',
    title: '建て替え用の土地を購入したい',
    deal: 'sale',
    category: '土地',
    prefecture: '新潟県',
    city: '南魚沼市',
    budget: 18_000_000,
    moveInDate: '2026-07-05',
    status: '成約',
    ownerUserId: 'nakamura-estate',
    createdAt: at('06-28 10:00'),
    updatedAt: at('07-05 15:40'),
    moderationStatus: 'approved',
    moderatedAt: at('06-28 10:30'),
  },
]

function lease(
  input: Omit<
    Lease,
    | 'months'
    | 'rentTotal'
    | 'deposit'
    | 'keyMoney'
    | 'initialCost'
    | 'createdAt'
    | 'updatedAt'
  > & {
    depositMonths?: number
    keyMoneyMonths?: number
    createdAt: string
    updatedAt: string
  },
): Lease {
  const { depositMonths, keyMoneyMonths, ...rest } = input
  const months = countLeaseMonths(input.startDate, input.endDate)
  const cost = calculateInitialCost({
    rentPerMonth: input.rentPerMonth,
    depositMonths,
    keyMoneyMonths,
  })
  return {
    ...rest,
    months,
    rentTotal: months * input.rentPerMonth,
    deposit: cost.deposit,
    keyMoney: cost.keyMoney,
    initialCost: cost.total,
  }
}

const leases: Lease[] = [
  lease({
    id: 'r-101',
    listingId: 'apt-001',
    tenantUserId: 'demo-user',
    startDate: '2026-10-05',
    endDate: '2026-10-08',
    rentPerMonth: 22_000,
    salePrice: 18_800_000,
    creditRate: 50,
    creditCap: 5_000_000,
    status: 'requested',
    createdAt: at('09-12 20:15'),
    updatedAt: at('09-12 20:15'),
  }),
  lease({
    id: 'r-102',
    listingId: 'cml-005',
    tenantUserId: 'suzuki',
    startDate: '2026-09-10',
    endDate: '2026-09-16',
    rentPerMonth: 12_000,
    status: 'active',
    createdAt: at('09-01 09:30'),
    updatedAt: at('09-10 08:00'),
  }),
  lease({
    id: 'r-103',
    listingId: 'apt-003',
    tenantUserId: 'demo-user',
    startDate: '2026-08-20',
    endDate: '2026-08-24',
    rentPerMonth: 18_000,
    salePrice: 9_600_000,
    creditRate: 50,
    creditCap: 2_500_000,
    status: 'completed',
    createdAt: at('08-10 12:00'),
    updatedAt: at('08-25 09:10'),
  }),
  lease({
    id: 'r-104',
    listingId: 'hse-002',
    tenantUserId: 'demo-admin',
    startDate: '2026-10-01',
    endDate: '2026-10-03',
    rentPerMonth: 45_000,
    salePrice: 24_500_000,
    creditRate: 50,
    creditCap: 6_000_000,
    status: 'requested',
    createdAt: at('09-13 08:50'),
    updatedAt: at('09-13 08:50'),
  }),
  lease({
    id: 'r-105',
    listingId: 'apt-001',
    tenantUserId: 'ito-estate',
    startDate: '2026-07-01',
    endDate: '2026-07-05',
    rentPerMonth: 22_000,
    salePrice: 18_800_000,
    creditRate: 50,
    creditCap: 5_000_000,
    status: 'completed',
    createdAt: at('06-20 15:00'),
    updatedAt: at('07-06 10:00'),
  }),
  lease({
    id: 'r-106',
    listingId: 'lnd-004',
    tenantUserId: 'takahashi',
    startDate: '2026-09-01',
    endDate: '2026-09-02',
    rentPerMonth: 2_500,
    status: 'cancelled',
    createdAt: at('08-28 19:00'),
    updatedAt: at('08-30 08:20'),
  }),
  lease({
    id: 'r-107',
    listingId: 'cml-106',
    tenantUserId: 'demo-user',
    startDate: '2026-09-12',
    endDate: '2026-09-18',
    rentPerMonth: 14_000,
    status: 'active',
    createdAt: at('09-03 10:00'),
    updatedAt: at('09-12 07:30'),
  }),
  lease({
    id: 'r-108',
    listingId: 'hse-002',
    tenantUserId: 'suzuki',
    startDate: '2026-06-10',
    endDate: '2026-06-12',
    rentPerMonth: 45_000,
    salePrice: 24_500_000,
    creditRate: 50,
    creditCap: 6_000_000,
    status: 'completed',
    createdAt: at('05-30 13:00'),
    updatedAt: at('06-13 11:00'),
  }),
]

const orders: Order[] = [
  {
    id: 'o-101',
    listingId: 'hse-002',
    buyerUserId: 'suzuki',
    sellerUserId: 'demo-seller',
    price: 24_500_000,
    status: 'requested',
    message: '6月にレンタルした際の状態が良かったので購入したいです。',
    createdAt: at('09-13 09:40'),
    updatedAt: at('09-13 09:40'),
  },
  {
    id: 'o-102',
    listingId: 'apt-006',
    buyerUserId: 'demo-user',
    sellerUserId: 'minato-chintai',
    price: 21_000_000,
    status: 'requested',
    message: '輸送は運搬マッチングで手配する予定です。',
    createdAt: at('09-11 21:00'),
    updatedAt: at('09-11 21:00'),
  },
  {
    id: 'o-103',
    listingId: 'lnd-004',
    buyerUserId: 'ito-estate',
    sellerUserId: 'kobayashi-kanri',
    price: 128_000,
    status: 'accepted',
    createdAt: at('09-09 10:00'),
    updatedAt: at('09-10 09:15'),
  },
  {
    id: 'o-104',
    listingId: 'lnd-104',
    buyerUserId: 'demo-user',
    sellerUserId: 'demo-seller',
    price: 98_000,
    status: 'completed',
    createdAt: at('08-05 12:00'),
    updatedAt: at('08-12 16:00'),
  },
  {
    id: 'o-105',
    listingId: 'hse-105',
    buyerUserId: 'kato',
    sellerUserId: 'nakamura-estate',
    price: 1_450_000,
    status: 'completed',
    createdAt: at('06-20 09:00'),
    updatedAt: at('07-02 12:00'),
  },
  {
    id: 'o-106',
    listingId: 'apt-006',
    buyerUserId: 'demo-admin',
    sellerUserId: 'minato-chintai',
    price: 21_000_000,
    status: 'cancelled',
    message: '検証用の申込です。',
    createdAt: at('09-02 15:00'),
    updatedAt: at('09-03 09:00'),
  },
]

const submissions: Submission[] = [
  {
    id: 's-101',
    kind: 'listingInquiry',
    targetId: 'apt-001',
    userId: 'suzuki',
    receivedAt: at('09-13 10:05'),
    payload: {
      mode: 'rent',
      name: '鈴木さん',
      email: 'suzuki@example.com',
      preferredDate: '2026-10-20',
      message: '10月下旬に1週間ほど借りたいです。ロータリーは付属しますか？',
    },
  },
  {
    id: 's-102',
    kind: 'listingInquiry',
    targetId: 'hse-002',
    userId: 'demo-user',
    receivedAt: at('09-11 19:20'),
    payload: {
      mode: 'question',
      name: '利用者デモ',
      email: 'user@example.com',
      message: '乾燥機との組み合わせは相談できますか？',
    },
    status: 'in_progress',
  },
  {
    id: 's-103',
    kind: 'listingInquiry',
    targetId: 'lnd-004',
    userId: 'kato',
    receivedAt: at('09-06 08:00'),
    payload: {
      mode: 'buy',
      name: '加藤さん',
      email: 'kato@example.com',
      message: '購入希望です。引き取りに伺えます。',
    },
    status: 'agreed',
  },
  {
    id: 's-104',
    kind: 'listingInquiry',
    targetId: 'cml-005',
    userId: 'demo-admin',
    receivedAt: at('09-12 11:30'),
    payload: {
      mode: 'rent',
      name: '運営デモ',
      email: 'admin@example.com',
      preferredDate: '2026-09-25',
      message: '講習用に2日間借りられますか？',
    },
  },
  {
    id: 's-105',
    kind: 'requestProposal',
    targetId: 'pr-101',
    userId: 'okada',
    receivedAt: at('09-08 12:00'),
    payload: {
      name: '岡田不動産',
      email: 'okada@example.com',
      vehicle: '2tトラック',
      availableDate: '2026-09-13',
      message: '当日午前に伺えます。',
    },
    status: 'agreed',
  },
  {
    id: 's-106',
    kind: 'requestProposal',
    targetId: 'pr-01',
    userId: 'hokuriku-kanri',
    receivedAt: at('09-13 09:55'),
    payload: {
      name: '北陸管理',
      email: 'hokuriku-unso@example.com',
      vehicle: '4tトラック',
      availableDate: '2026-09-28',
      message: '大仙から天童は定期便のルートです。',
    },
  },
  {
    id: 's-107',
    kind: 'requestProposal',
    targetId: 'pr-05',
    userId: 'demo-user',
    receivedAt: at('09-12 16:45'),
    payload: {
      name: '利用者デモ',
      email: 'user@example.com',
      vehicle: '2tトラック',
      availableDate: '2026-10-12',
    },
  },
  {
    id: 's-108',
    kind: 'requestInquiry',
    targetId: 'pr-02',
    userId: 'yamamoto-jisho',
    receivedAt: at('09-10 13:10'),
    payload: { message: '積み込みにフォークリフトは用意されますか？' },
    status: 'in_progress',
  },
  {
    id: 's-109',
    kind: 'requestProposal',
    targetId: 'pr-102',
    userId: 'hokuriku-kanri',
    receivedAt: at('09-06 09:00'),
    payload: {
      name: '北陸管理',
      email: 'hokuriku-unso@example.com',
      vehicle: '4tトラック',
      availableDate: '2026-09-20',
    },
    status: 'agreed',
  },
  {
    id: 's-110',
    kind: 'requestProposal',
    targetId: 'pr-104',
    userId: 'yamamoto-jisho',
    receivedAt: at('06-29 10:00'),
    payload: {
      name: '山本地所',
      email: 'yamamoto-transport@example.com',
      vehicle: 'トレーラー',
      availableDate: '2026-07-05',
    },
    status: 'agreed',
  },
  {
    id: 's-111',
    kind: 'listingInquiry',
    targetId: 'apt-006',
    userId: 'takahashi',
    receivedAt: at('08-20 20:00'),
    payload: {
      mode: 'buy',
      name: '高橋さん',
      email: 'takahashi@example.com',
      message: '値下げの相談はできますか？',
    },
    status: 'declined',
  },
  {
    id: 's-112',
    kind: 'requestInquiry',
    targetId: 'pr-01',
    userId: 'demo-user',
    receivedAt: at('09-12 09:00'),
    payload: { message: '希望日の前日搬入でも大丈夫ですか？' },
    status: 'in_progress',
  },
]

const messages: Message[] = [
  {
    id: 'm-101',
    threadId: 's-102',
    senderUserId: 'demo-seller',
    body: '乾燥機は別途ご相談ください。搬入も合わせて見積もりします。',
    createdAt: at('09-12 08:30'),
  },
  {
    id: 'm-102',
    threadId: 's-112',
    senderUserId: 'demo-seller',
    body: '前日搬入で問題ありません。倉庫の鍵は当日お渡しします。',
    createdAt: at('09-12 12:10'),
  },
  {
    id: 'm-103',
    threadId: 's-103',
    senderUserId: 'kobayashi-kanri',
    body: 'ありがとうございます。9月中の引き取りでお願いします。',
    createdAt: at('09-06 18:00'),
  },
  {
    id: 'm-104',
    threadId: 's-108',
    senderUserId: 'demo-seller',
    body: 'フォークリフトは出発地に用意があります。',
    createdAt: at('09-10 15:00'),
  },
]

const reviews: Review[] = [
  {
    id: 'rv-101',
    listingId: 'lnd-104',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'demo-user',
    sourceKind: 'order',
    sourceId: 'o-104',
    rating: 5,
    comment: '説明どおりほぼ新品でした。引き渡しもスムーズ。',
    createdAt: at('08-13 21:00'),
  },
  {
    id: 'rv-102',
    listingId: 'apt-003',
    sellerUserId: 'tamura',
    reviewerUserId: 'demo-user',
    sourceKind: 'lease',
    sourceId: 'r-103',
    rating: 5,
    comment: '整備が行き届いていて、初めての6条でも扱いやすかったです。',
    createdAt: at('08-26 07:40'),
  },
  {
    id: 'rv-103',
    listingId: 'apt-001',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'ito-estate',
    sourceKind: 'lease',
    sourceId: 'r-105',
    rating: 4,
    comment: '状態は良好。返却時の清掃基準を事前に聞いておくと安心です。',
    createdAt: at('07-07 09:00'),
  },
  {
    id: 'rv-104',
    listingId: 'hse-105',
    sellerUserId: 'nakamura-estate',
    reviewerUserId: 'kato',
    sourceKind: 'order',
    sourceId: 'o-105',
    rating: 4,
    comment: '価格相応。運搬の手配まで相談に乗ってもらえました。',
    createdAt: at('07-04 19:30'),
  },
  {
    id: 'rv-105',
    listingId: 'hse-002',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'suzuki',
    sourceKind: 'lease',
    sourceId: 'r-108',
    rating: 3,
    comment: '機体は問題なし。受け渡し時間の連絡がやや遅めでした。',
    createdAt: at('06-14 20:10'),
  },
]

const agentProfiles: AgentProfile[] = [
  {
    id: 'demo-user',
    name: '利用者デモ',
    kind: '個人',
    prefecture: '東京都',
    handledCategories: ['マンション', '戸建'],
    serviceAreas: ['東京都', '神奈川県', '埼玉県'],
    note: '週末中心に内見の案内ができます。',
    createdAt: at('08-15 10:00'),
    updatedAt: at('08-15 10:00'),
  },
  {
    id: 'okada',
    name: '岡田不動産',
    kind: '宅建業者',
    prefecture: '東京都',
    handledCategories: ['マンション', '土地'],
    serviceAreas: ['東京都'],
    createdAt: at('07-10 09:00'),
    updatedAt: at('07-10 09:00'),
  },
  {
    id: 'hokuriku-kanri',
    name: '北陸管理',
    kind: '管理会社',
    prefecture: '石川県',
    handledCategories: ['マンション', '戸建', '事業用'],
    serviceAreas: ['石川県', '富山県', '福井県', '新潟県', '長野県'],
    note: '北陸〜信越の賃貸管理を担当しています。',
    createdAt: at('05-12 11:00'),
    updatedAt: at('08-01 11:00'),
  },
  {
    id: 'yamamoto-jisho',
    name: '山本地所',
    kind: '法人',
    prefecture: '北海道',
    handledCategories: ['土地', '事業用'],
    serviceAreas: ['北海道', '宮城県', '埼玉県'],
    createdAt: at('04-20 09:00'),
    updatedAt: at('04-20 09:00'),
  },
]

const notifications: Notification[] = [
  {
    id: 'n-101',
    userId: 'demo-seller',
    kind: 'inquiry',
    title: '問い合わせが届きました',
    body: 'クボタ トラクター 45馬力 GLシリーズ',
    href: '/account/threads/s-101',
    createdAt: at('09-13 10:05'),
  },
  {
    id: 'n-102',
    userId: 'demo-seller',
    kind: 'application',
    title: '応募が届きました',
    body: 'コンバイン 4条刈',
    href: '/account/threads/s-106',
    createdAt: at('09-13 09:55'),
  },
  {
    id: 'n-103',
    userId: 'demo-seller',
    kind: 'lease',
    title: '購入の申込が届きました',
    body: 'ヤンマー コンバイン 4条刈 AGシリーズ',
    href: '/account',
    createdAt: at('09-13 09:40'),
  },
  {
    id: 'n-104',
    userId: 'demo-seller',
    kind: 'lease',
    title: 'レンタルの申込が届きました',
    body: 'ヤンマー コンバイン 4条刈 AGシリーズ',
    href: '/account',
    createdAt: at('09-13 08:50'),
  },
  {
    id: 'n-105',
    userId: 'demo-seller',
    kind: 'application',
    title: '運搬が始まりました',
    body: 'トラクター 45馬力（キャビン付）',
    href: '/transport/tj-101',
    createdAt: at('09-13 08:05'),
  },
  {
    id: 'n-106',
    userId: 'demo-seller',
    kind: 'lease',
    title: 'レンタルの申込が届きました',
    body: 'クボタ トラクター 45馬力 GLシリーズ',
    href: '/account',
    createdAt: at('09-12 20:15'),
    readAt: at('09-12 21:00'),
  },
  {
    id: 'n-107',
    userId: 'demo-seller',
    kind: 'application',
    title: '案件への質問が届きました',
    body: 'トラクター 45馬力',
    href: '/account/threads/s-108',
    createdAt: at('09-10 13:10'),
    readAt: at('09-10 14:55'),
  },
  {
    id: 'n-108',
    userId: 'demo-user',
    kind: 'reply',
    title: '返信が届きました',
    body: 'ヤンマー コンバイン 4条刈 AGシリーズ',
    href: '/account/threads/s-102',
    createdAt: at('09-12 08:30'),
  },
  {
    id: 'n-109',
    userId: 'demo-user',
    kind: 'reply',
    title: '返信が届きました',
    body: 'コンバイン 4条刈',
    href: '/account/threads/s-112',
    createdAt: at('09-12 12:10'),
  },
  {
    id: 'n-110',
    userId: 'demo-user',
    kind: 'lease',
    title: `レンタルが「${leaseStatusLabels.active}」になりました`,
    body: '農業用ドローン 16Lタンク 散布用',
    href: '/account',
    createdAt: at('09-12 07:30'),
  },
  {
    id: 'n-111',
    userId: 'demo-user',
    kind: 'lease',
    title: `レンタルが「${leaseStatusLabels.completed}」になりました`,
    body: 'イセキ 田植機 6条植 さなえ',
    href: '/account',
    createdAt: at('08-25 09:10'),
    readAt: at('08-25 12:00'),
  },
  {
    id: 'n-112',
    userId: 'demo-user',
    kind: 'lease',
    title: `購入が「${orderStatusLabels.completed}」になりました`,
    body: 'ホンダ 管理機 F220 サラダ',
    href: '/account',
    createdAt: at('08-12 16:00'),
    readAt: at('08-12 18:30'),
  },
  {
    id: 'n-113',
    userId: 'demo-admin',
    kind: 'moderation',
    title: '出品が承認されました',
    body: 'クボタ 管理機 陽菜 TRS70',
    href: '/listings/til-103',
    createdAt: at('08-30 11:20'),
    readAt: at('08-30 11:25'),
  },
  {
    id: 'n-114',
    userId: 'demo-admin',
    kind: 'lease',
    title: `購入が「${orderStatusLabels.cancelled}」になりました`,
    body: 'ジョンディア トラクター 90馬力 大規模向け',
    href: '/account',
    createdAt: at('09-03 09:00'),
  },
]

const threadReads: ThreadRead[] = [
  { threadId: 's-102', userId: 'demo-seller', readAt: at('09-12 08:30') },
  { threadId: 's-112', userId: 'demo-seller', readAt: at('09-12 12:10') },
  { threadId: 's-108', userId: 'demo-seller', readAt: at('09-10 15:00') },
  { threadId: 's-105', userId: 'demo-seller', readAt: at('09-09 18:00') },
  { threadId: 's-103', userId: 'kobayashi-kanri', readAt: at('09-06 18:00') },
].map((read) => ({ id: `${read.threadId}:${read.userId}`, ...read }))

const accountStatuses: AccountStatus[] = [
  {
    id: 'watanabe',
    status: 'suspended',
    note: '本人確認の書類が未提出',
    updatedAt: at('09-04 10:00'),
  },
]

type EventSeed = [DealKind, string, string, string | undefined, string, string?]

/** [kind, dealId, status, actor, when, note] — order does not matter. */
const eventSeeds: EventSeed[] = [
  [
    'order',
    'o-101',
    'requested',
    'suzuki',
    '09-13 09:40',
    '6月にレンタルした際の状態が良かったので購入したいです。',
  ],
  [
    'order',
    'o-102',
    'requested',
    'demo-user',
    '09-11 21:00',
    '輸送は運搬マッチングで手配する予定です。',
  ],
  ['order', 'o-103', 'requested', 'ito-estate', '09-09 10:00'],
  ['order', 'o-103', 'accepted', 'kobayashi-kanri', '09-10 09:15'],
  ['order', 'o-104', 'requested', 'demo-user', '08-05 12:00'],
  ['order', 'o-104', 'accepted', 'demo-seller', '08-06 08:00'],
  ['order', 'o-104', 'delivered', 'demo-seller', '08-10 14:00'],
  ['order', 'o-104', 'completed', 'demo-user', '08-12 16:00'],
  ['order', 'o-105', 'requested', 'kato', '06-20 09:00'],
  ['order', 'o-105', 'accepted', 'nakamura-estate', '06-21 07:30'],
  ['order', 'o-105', 'delivered', 'nakamura-estate', '06-30 11:00'],
  ['order', 'o-105', 'completed', 'kato', '07-02 12:00'],
  [
    'order',
    'o-106',
    'requested',
    'demo-admin',
    '09-02 15:00',
    '検証用の申込です。',
  ],
  ['order', 'o-106', 'cancelled', 'demo-admin', '09-03 09:00'],
  [
    'lease',
    'r-101',
    'requested',
    'demo-user',
    '09-12 20:15',
    '2026-10-05 〜 2026-10-08',
  ],
  [
    'lease',
    'r-102',
    'requested',
    'suzuki',
    '09-01 09:30',
    '2026-09-10 〜 2026-09-16',
  ],
  ['lease', 'r-102', 'active', 'sky-realty', '09-10 08:00'],
  [
    'lease',
    'r-103',
    'requested',
    'demo-user',
    '08-10 12:00',
    '2026-08-20 〜 2026-08-24',
  ],
  ['lease', 'r-103', 'active', 'tamura', '08-20 09:00'],
  ['lease', 'r-103', 'completed', 'tamura', '08-25 09:10'],
  [
    'lease',
    'r-104',
    'requested',
    'demo-admin',
    '09-13 08:50',
    '2026-10-01 〜 2026-10-03',
  ],
  [
    'lease',
    'r-105',
    'requested',
    'ito-estate',
    '06-20 15:00',
    '2026-07-01 〜 2026-07-05',
  ],
  ['lease', 'r-105', 'active', 'demo-seller', '07-01 08:30'],
  ['lease', 'r-105', 'completed', 'demo-seller', '07-06 10:00'],
  [
    'lease',
    'r-106',
    'requested',
    'takahashi',
    '08-28 19:00',
    '2026-09-01 〜 2026-09-02',
  ],
  ['lease', 'r-106', 'cancelled', 'takahashi', '08-30 08:20'],
  [
    'lease',
    'r-107',
    'requested',
    'demo-user',
    '09-03 10:00',
    '2026-09-12 〜 2026-09-18',
  ],
  ['lease', 'r-107', 'active', 'demo-seller', '09-12 07:30'],
  [
    'lease',
    'r-108',
    'requested',
    'suzuki',
    '05-30 13:00',
    '2026-06-10 〜 2026-06-12',
  ],
  ['lease', 'r-108', 'active', 'demo-seller', '06-10 09:00'],
  ['lease', 'r-108', 'completed', 'demo-seller', '06-13 11:00'],
  ['propertyRequest', 'pr-101', '募集中', 'demo-seller', '09-08 09:00'],
  ['propertyRequest', 'pr-101', 'approved', undefined, '09-08 09:30'],
  ['propertyRequest', 'pr-101', '調整中', 'demo-seller', '09-09 18:00'],
  ['propertyRequest', 'pr-101', '運搬中', 'okada', '09-13 08:05'],
  ['propertyRequest', 'pr-102', '募集中', 'ito-estate', '09-05 14:00'],
  ['propertyRequest', 'pr-102', 'approved', undefined, '09-05 14:20'],
  ['propertyRequest', 'pr-102', '調整中', 'ito-estate', '09-11 17:30'],
  ['propertyRequest', 'pr-103', '募集中', 'kato', '09-13 07:45'],
  ['propertyRequest', 'pr-104', '募集中', 'nakamura-estate', '06-28 10:00'],
  ['propertyRequest', 'pr-104', 'approved', undefined, '06-28 10:30'],
  ['propertyRequest', 'pr-104', '調整中', 'nakamura-estate', '06-30 09:00'],
  ['propertyRequest', 'pr-104', '運搬中', 'yamamoto-jisho', '07-05 08:00'],
  ['propertyRequest', 'pr-104', '完了', 'nakamura-estate', '07-05 15:40'],
]

const dealEvents: DealEvent[] = eventSeeds
  .map(([dealKind, dealId, status, actorUserId, when, note], index) => ({
    id: `ev-${String(index + 101)}`,
    dealKind,
    dealId,
    status,
    actorUserId,
    note,
    createdAt: at(when),
  }))
  .sort((a, b) => b.createdAt.localeCompare(a.createdAt))

export const demoActivity: DemoActivity = {
  listings,
  propertyRequests,
  submissions,
  messages,
  leases,
  orders,
  reviews,
  agentProfiles,
  notifications,
  threadReads,
  accountStatuses,
  dealEvents,
}
