import 'server-only'
import { generateListings } from './generated-listings'
import { listings as catalogListings } from './data'

import { orderStatusLabels, type Listing, type TransportJob } from '@/lib/data'
import { countRentalDays, rentalStatusLabels } from '@/lib/rent-to-own'
import type {
  AccountStatus,
  CarrierProfile,
  DealEvent,
  DealKind,
  Message,
  Notification,
  Order,
  Rental,
  Review,
  Submission,
  ThreadRead,
} from './store/types'

/**
 * What the marketplace looks like after a few months of use: purchases,
 * rentals, threads, hauls, and reviews between the demo accounts and the
 * personas. Loaded on top of the sample listings unless `DEMO_ACTIVITY=off`.
 */
export type DemoActivity = {
  listings: Listing[]
  transportJobs: TransportJob[]
  submissions: Submission[]
  messages: Message[]
  rentals: Rental[]
  orders: Order[]
  reviews: Review[]
  carrierProfiles: CarrierProfile[]
  notifications: Notification[]
  threadReads: ThreadRead[]
  accountStatuses: AccountStatus[]
  dealEvents: DealEvent[]
}

/** `at('09-13 10:30')` → ISO timestamp in 2026, JST. */
function at(stamp: string): string {
  const [date, time] = stamp.split(' ')
  return new Date(`2026-${date}T${time}:00+09:00`).toISOString()
}

const history = [
  {
    id: 'trc-101',
    ownerUserId: 'demo-seller',
    moderationStatus: 'pending' as const,
  },
  {
    id: 'cmb-102',
    ownerUserId: 'yamada-nosan',
    moderationStatus: 'pending' as const,
  },
  {
    id: 'til-103',
    ownerUserId: 'demo-admin',
    moderationStatus: 'approved' as const,
  },
  {
    id: 'til-104',
    ownerUserId: 'demo-seller',
    moderationStatus: 'approved' as const,
    withdrawnAt: at('08-12 16:00'),
  },
  {
    id: 'rpl-105',
    ownerUserId: 'nakamura-farm',
    moderationStatus: 'approved' as const,
    withdrawnAt: at('07-02 12:00'),
  },
  {
    id: 'drn-106',
    ownerUserId: 'demo-seller',
    moderationStatus: 'approved' as const,
  },
]
const listings: Listing[] = generateListings(6, 101).map((listing, index) => ({
  ...listing,
  ...history[index],
  seller: {
    ...listing.seller,
    name:
      history[index].ownerUserId === 'demo-admin' ? '運営デモ' : '掲載者デモ',
  },
  createdAt: at('08-01 10:00'),
  updatedAt: at('09-13 09:10'),
}))

const transportJobs: TransportJob[] = [
  {
    id: 'tj-101',
    item: 'ふたり暮らしの引越し',
    from: '新潟県 長岡市',
    to: '新潟県 新潟市',
    distanceKm: 60,
    weight: '2tトラック1台分',
    desiredDate: '9/13 午前',
    reward: 18_000,
    status: '運搬中',
    ownerUserId: 'demo-seller',
    createdAt: at('09-08 09:00'),
    updatedAt: at('09-13 08:05'),
    moderationStatus: 'approved',
    moderatedAt: at('09-08 09:30'),
  },
  {
    id: 'tj-102',
    item: '新居への家具配送',
    from: '富山県 砺波市',
    to: '長野県 飯山市',
    distanceKm: 130,
    weight: '家具5点',
    desiredDate: '9/20 終日',
    reward: 32_000,
    status: '調整中',
    ownerUserId: 'ito-farm',
    createdAt: at('09-05 14:00'),
    updatedAt: at('09-11 17:30'),
    moderationStatus: 'approved',
    moderatedAt: at('09-05 14:20'),
  },
  {
    id: 'tj-103',
    item: '段ボールとデスクの配送',
    from: '群馬県 前橋市',
    to: '埼玉県 深谷市',
    distanceKm: 45,
    weight: '段ボール10箱・デスク',
    desiredDate: '相談',
    reward: 7_000,
    status: '募集中',
    ownerUserId: 'kato',
    createdAt: at('09-13 07:45'),
    updatedAt: at('09-13 07:45'),
    moderationStatus: 'pending',
  },
  {
    id: 'tj-104',
    item: '単身引越し・家具家電一式',
    from: '新潟県 南魚沼市',
    to: '群馬県 高崎市',
    distanceKm: 140,
    weight: '単身・家具家電あり',
    desiredDate: '7/5 午前',
    reward: 28_000,
    status: '完了',
    ownerUserId: 'nakamura-farm',
    createdAt: at('06-28 10:00'),
    updatedAt: at('07-05 15:40'),
    moderationStatus: 'approved',
    moderatedAt: at('06-28 10:30'),
  },
]

function rental(
  input: Omit<Rental, 'days' | 'rentTotal' | 'createdAt' | 'updatedAt'> & {
    createdAt: string
    updatedAt: string
  },
): Rental {
  const days = countRentalDays(input.startDate, input.endDate)
  return { ...input, days, rentTotal: days * input.rentPerDay }
}

const rentals: Rental[] = [
  rental({
    id: 'r-101',
    listingId: 'trc-001',
    renterUserId: 'demo-user',
    startDate: '2026-10-05',
    endDate: '2026-10-08',
    rentPerDay: 22_000,
    salePrice: 18_800_000,
    creditRate: 50,
    creditCap: 5_000_000,
    status: 'requested',
    createdAt: at('09-12 20:15'),
    updatedAt: at('09-12 20:15'),
  }),
  rental({
    id: 'r-102',
    listingId: 'drn-005',
    renterUserId: 'suzuki',
    startDate: '2026-09-10',
    endDate: '2026-09-16',
    rentPerDay: 12_000,
    status: 'active',
    createdAt: at('09-01 09:30'),
    updatedAt: at('09-10 08:00'),
  }),
  rental({
    id: 'r-103',
    listingId: 'rpl-003',
    renterUserId: 'demo-user',
    startDate: '2026-08-20',
    endDate: '2026-08-24',
    rentPerDay: 18_000,
    salePrice: 9_600_000,
    creditRate: 50,
    creditCap: 2_500_000,
    status: 'completed',
    createdAt: at('08-10 12:00'),
    updatedAt: at('08-25 09:10'),
  }),
  rental({
    id: 'r-104',
    listingId: 'cmb-002',
    renterUserId: 'demo-admin',
    startDate: '2026-10-01',
    endDate: '2026-10-03',
    rentPerDay: 45_000,
    salePrice: 24_500_000,
    creditRate: 50,
    creditCap: 6_000_000,
    status: 'requested',
    createdAt: at('09-13 08:50'),
    updatedAt: at('09-13 08:50'),
  }),
  rental({
    id: 'r-105',
    listingId: 'trc-001',
    renterUserId: 'ito-farm',
    startDate: '2026-07-01',
    endDate: '2026-07-05',
    rentPerDay: 22_000,
    salePrice: 18_800_000,
    creditRate: 50,
    creditCap: 5_000_000,
    status: 'completed',
    createdAt: at('06-20 15:00'),
    updatedAt: at('07-06 10:00'),
  }),
  rental({
    id: 'r-106',
    listingId: 'til-004',
    renterUserId: 'takahashi',
    startDate: '2026-09-01',
    endDate: '2026-09-02',
    rentPerDay: 2_500,
    status: 'cancelled',
    createdAt: at('08-28 19:00'),
    updatedAt: at('08-30 08:20'),
  }),
  rental({
    id: 'r-107',
    listingId: 'drn-106',
    renterUserId: 'demo-user',
    startDate: '2026-09-12',
    endDate: '2026-09-18',
    rentPerDay: 14_000,
    status: 'active',
    createdAt: at('09-03 10:00'),
    updatedAt: at('09-12 07:30'),
  }),
  rental({
    id: 'r-108',
    listingId: 'cmb-002',
    renterUserId: 'suzuki',
    startDate: '2026-06-10',
    endDate: '2026-06-12',
    rentPerDay: 45_000,
    salePrice: 24_500_000,
    creditRate: 50,
    creditCap: 6_000_000,
    status: 'completed',
    createdAt: at('05-30 13:00'),
    updatedAt: at('06-13 11:00'),
  }),
]

const orders: Order[] = [
  {
    id: 'o-101',
    listingId: 'cmb-002',
    buyerUserId: 'suzuki',
    sellerUserId: 'demo-seller',
    price: 24_500_000,
    status: 'requested',
    message: '6月の内見で住環境が気に入り、購入を検討しています。',
    createdAt: at('09-13 09:40'),
    updatedAt: at('09-13 09:40'),
  },
  {
    id: 'o-102',
    listingId: 'trc-006',
    buyerUserId: 'demo-user',
    sellerUserId: 'tokachi-agri',
    price: 21_000_000,
    status: 'requested',
    message: '入居時の引越しもこちらで相談する予定です。',
    createdAt: at('09-11 21:00'),
    updatedAt: at('09-11 21:00'),
  },
  {
    id: 'o-103',
    listingId: 'til-004',
    buyerUserId: 'ito-farm',
    sellerUserId: 'kobayashi-engei',
    price: 128_000,
    status: 'accepted',
    createdAt: at('09-09 10:00'),
    updatedAt: at('09-10 09:15'),
  },
  {
    id: 'o-104',
    listingId: 'til-104',
    buyerUserId: 'demo-user',
    sellerUserId: 'demo-seller',
    price: 98_000,
    status: 'completed',
    createdAt: at('08-05 12:00'),
    updatedAt: at('08-12 16:00'),
  },
  {
    id: 'o-105',
    listingId: 'rpl-105',
    buyerUserId: 'kato',
    sellerUserId: 'nakamura-farm',
    price: 1_450_000,
    status: 'completed',
    createdAt: at('06-20 09:00'),
    updatedAt: at('07-02 12:00'),
  },
  {
    id: 'o-106',
    listingId: 'trc-006',
    buyerUserId: 'demo-admin',
    sellerUserId: 'tokachi-agri',
    price: 21_000_000,
    status: 'cancelled',
    message: '検証用の申込です。',
    createdAt: at('09-02 15:00'),
    updatedAt: at('09-03 09:00'),
  },
]

const submissions: Submission[] = [
  {
    id: 's-101',
    kind: 'listingInquiry',
    targetId: 'trc-001',
    userId: 'suzuki',
    receivedAt: at('09-13 10:05'),
    payload: {
      mode: 'rent',
      name: '鈴木さん',
      email: 'suzuki@example.com',
      preferredDate: '2026-10-20',
      message: '10月下旬の入居を希望しています。駐車場の空きはありますか？',
    },
  },
  {
    id: 's-102',
    kind: 'listingInquiry',
    targetId: 'cmb-002',
    userId: 'demo-user',
    receivedAt: at('09-11 19:20'),
    payload: {
      mode: 'question',
      name: '利用者デモ',
      email: 'user@example.com',
      message: '駐車場と収納の広さについて相談できますか？',
    },
    status: 'in_progress',
  },
  {
    id: 's-103',
    kind: 'listingInquiry',
    targetId: 'til-004',
    userId: 'kato',
    receivedAt: at('09-06 08:00'),
    payload: {
      mode: 'buy',
      name: '加藤さん',
      email: 'kato@example.com',
      message: '購入を検討しています。内見に伺えます。',
    },
    status: 'agreed',
  },
  {
    id: 's-104',
    kind: 'listingInquiry',
    targetId: 'drn-005',
    userId: 'demo-admin',
    receivedAt: at('09-12 11:30'),
    payload: {
      mode: 'rent',
      name: '運営デモ',
      email: 'admin@example.com',
      preferredDate: '2026-09-25',
      message: '店舗としての利用条件と入居時期を相談できますか？',
    },
  },
  {
    id: 's-105',
    kind: 'transportApplication',
    targetId: 'tj-101',
    userId: 'okada',
    receivedAt: at('09-08 12:00'),
    payload: {
      name: '岡田さん',
      email: 'okada@example.com',
      vehicle: '2tトラック',
      availableDate: '2026-09-13',
      message: '当日午前に伺えます。',
    },
    status: 'agreed',
  },
  {
    id: 's-106',
    kind: 'transportApplication',
    targetId: 'tj-01',
    userId: 'hokuriku-unso',
    receivedAt: at('09-13 09:55'),
    payload: {
      name: '北陸運送',
      email: 'hokuriku-unso@example.com',
      vehicle: '4tトラック',
      availableDate: '2026-09-28',
      message: '大仙から天童は定期便のルートです。',
    },
  },
  {
    id: 's-107',
    kind: 'transportApplication',
    targetId: 'tj-05',
    userId: 'demo-user',
    receivedAt: at('09-12 16:45'),
    payload: {
      name: '利用者デモ',
      email: 'user@example.com',
      vehicle: '2tトラック',
      availableDate: '2026-10-12',
    },
  },
  {
    id: 's-108',
    kind: 'transportInquiry',
    targetId: 'tj-02',
    userId: 'yamamoto-transport',
    receivedAt: at('09-10 13:10'),
    payload: { message: '搬出元にエレベーターはありますか？' },
    status: 'in_progress',
  },
  {
    id: 's-109',
    kind: 'transportApplication',
    targetId: 'tj-102',
    userId: 'hokuriku-unso',
    receivedAt: at('09-06 09:00'),
    payload: {
      name: '北陸運送',
      email: 'hokuriku-unso@example.com',
      vehicle: '4tトラック',
      availableDate: '2026-09-20',
    },
    status: 'agreed',
  },
  {
    id: 's-110',
    kind: 'transportApplication',
    targetId: 'tj-104',
    userId: 'yamamoto-transport',
    receivedAt: at('06-29 10:00'),
    payload: {
      name: '山本トランスポート',
      email: 'yamamoto-transport@example.com',
      vehicle: 'トレーラー',
      availableDate: '2026-07-05',
    },
    status: 'agreed',
  },
  {
    id: 's-111',
    kind: 'listingInquiry',
    targetId: 'trc-006',
    userId: 'takahashi',
    receivedAt: at('08-20 20:00'),
    payload: {
      mode: 'buy',
      name: '高橋さん',
      email: 'takahashi@example.com',
      message: '値下げの相談はできますか？',
    },
    status: 'declined',
  },
  {
    id: 's-112',
    kind: 'transportInquiry',
    targetId: 'tj-01',
    userId: 'demo-user',
    receivedAt: at('09-12 09:00'),
    payload: { message: '希望日の前日搬入でも大丈夫ですか？' },
    status: 'in_progress',
  },
]

const messages: Message[] = [
  {
    id: 'm-101',
    threadId: 's-102',
    senderUserId: 'demo-seller',
    body: '駐車場は1台分あります。収納も内見時にご確認いただけます。',
    createdAt: at('09-12 08:30'),
  },
  {
    id: 'm-102',
    threadId: 's-112',
    senderUserId: 'demo-seller',
    body: '前日の搬入で問題ありません。新居の鍵は当日お渡しします。',
    createdAt: at('09-12 12:10'),
  },
  {
    id: 'm-103',
    threadId: 's-103',
    senderUserId: 'kobayashi-engei',
    body: 'ありがとうございます。9月中の内見日程をご相談ください。',
    createdAt: at('09-06 18:00'),
  },
  {
    id: 'm-104',
    threadId: 's-108',
    senderUserId: 'demo-seller',
    body: '搬出元にはエレベーターがあります。大型家具の寸法もお知らせします。',
    createdAt: at('09-10 15:00'),
  },
]

const reviews: Review[] = [
  {
    id: 'rv-101',
    listingId: 'til-104',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'demo-user',
    sourceKind: 'order',
    sourceId: 'o-104',
    rating: 5,
    comment: '説明どおり明るくきれいな室内でした。引き渡しもスムーズでした。',
    createdAt: at('08-13 21:00'),
  },
  {
    id: 'rv-102',
    listingId: 'rpl-003',
    sellerUserId: 'tamura',
    reviewerUserId: 'demo-user',
    sourceKind: 'rental',
    sourceId: 'r-103',
    rating: 5,
    comment:
      '管理が行き届いていて、周辺環境についても丁寧に説明いただけました。',
    createdAt: at('08-26 07:40'),
  },
  {
    id: 'rv-103',
    listingId: 'trc-001',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'ito-farm',
    sourceKind: 'rental',
    sourceId: 'r-105',
    rating: 4,
    comment: '室内の状態は良好。退去時の清掃条件も事前に確認できました。',
    createdAt: at('07-07 09:00'),
  },
  {
    id: 'rv-104',
    listingId: 'rpl-105',
    sellerUserId: 'nakamura-farm',
    reviewerUserId: 'kato',
    sourceKind: 'order',
    sourceId: 'o-105',
    rating: 4,
    comment: '条件に納得できました。引越しの手配まで相談に乗ってもらえました。',
    createdAt: at('07-04 19:30'),
  },
  {
    id: 'rv-105',
    listingId: 'cmb-002',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'suzuki',
    sourceKind: 'rental',
    sourceId: 'r-108',
    rating: 3,
    comment:
      '物件に問題はありませんでしたが、鍵の受け渡し時間の連絡がやや遅めでした。',
    createdAt: at('06-14 20:10'),
  },
]

const carrierProfiles: CarrierProfile[] = [
  {
    id: 'demo-user',
    name: '利用者デモ',
    kind: '個人',
    prefecture: '新潟県',
    vehicles: ['2tトラック'],
    serviceAreas: ['新潟県', '長野県', '富山県'],
    note: '週末中心に対応できます。',
    createdAt: at('08-15 10:00'),
    updatedAt: at('08-15 10:00'),
  },
  {
    id: 'okada',
    name: '岡田さん',
    kind: '個人',
    prefecture: '新潟県',
    vehicles: ['軽トラック', '2tトラック'],
    serviceAreas: ['新潟県'],
    createdAt: at('07-10 09:00'),
    updatedAt: at('07-10 09:00'),
  },
  {
    id: 'hokuriku-unso',
    name: '北陸運送',
    kind: '法人',
    prefecture: '石川県',
    vehicles: ['4tトラック', 'トレーラー'],
    serviceAreas: ['石川県', '富山県', '福井県', '新潟県', '秋田県', '山形県'],
    note: '北陸〜東北の定期便あり。',
    createdAt: at('05-12 11:00'),
    updatedAt: at('08-01 11:00'),
  },
  {
    id: 'yamamoto-transport',
    name: '山本トランスポート',
    kind: '法人',
    prefecture: '北海道',
    vehicles: ['4tトラック', 'トレーラー'],
    serviceAreas: ['北海道', '新潟県', '群馬県'],
    createdAt: at('04-20 09:00'),
    updatedAt: at('04-20 09:00'),
  },
]

function listingName(id: string): string {
  return (
    [...catalogListings, ...listings].find((listing) => listing.id === id)
      ?.name ?? '物件'
  )
}

const notifications: Notification[] = [
  {
    id: 'n-101',
    userId: 'demo-seller',
    kind: 'inquiry',
    title: '問い合わせが届きました',
    body: listingName('trc-001'),
    href: '/account/threads/s-101',
    createdAt: at('09-13 10:05'),
  },
  {
    id: 'n-102',
    userId: 'demo-seller',
    kind: 'application',
    title: '応募が届きました',
    body: 'ふたり暮らしの引越し',
    href: '/account/threads/s-106',
    createdAt: at('09-13 09:55'),
  },
  {
    id: 'n-103',
    userId: 'demo-seller',
    kind: 'rental',
    title: '購入の申込が届きました',
    body: listingName('cmb-002'),
    href: '/account',
    createdAt: at('09-13 09:40'),
  },
  {
    id: 'n-104',
    userId: 'demo-seller',
    kind: 'rental',
    title: 'レンタルの申込が届きました',
    body: listingName('cmb-002'),
    href: '/account',
    createdAt: at('09-13 08:50'),
  },
  {
    id: 'n-105',
    userId: 'demo-seller',
    kind: 'application',
    title: '引越しが始まりました',
    body: 'ふたり暮らしの引越し',
    href: '/transport/tj-101',
    createdAt: at('09-13 08:05'),
  },
  {
    id: 'n-106',
    userId: 'demo-seller',
    kind: 'rental',
    title: 'レンタルの申込が届きました',
    body: listingName('trc-001'),
    href: '/account',
    createdAt: at('09-12 20:15'),
    readAt: at('09-12 21:00'),
  },
  {
    id: 'n-107',
    userId: 'demo-seller',
    kind: 'application',
    title: '案件への質問が届きました',
    body: '単身引越し・家具家電一式',
    href: '/account/threads/s-108',
    createdAt: at('09-10 13:10'),
    readAt: at('09-10 14:55'),
  },
  {
    id: 'n-108',
    userId: 'demo-user',
    kind: 'reply',
    title: '返信が届きました',
    body: listingName('cmb-002'),
    href: '/account/threads/s-102',
    createdAt: at('09-12 08:30'),
  },
  {
    id: 'n-109',
    userId: 'demo-user',
    kind: 'reply',
    title: '返信が届きました',
    body: 'ふたり暮らしの引越し',
    href: '/account/threads/s-112',
    createdAt: at('09-12 12:10'),
  },
  {
    id: 'n-110',
    userId: 'demo-user',
    kind: 'rental',
    title: `レンタルが「${rentalStatusLabels.active}」になりました`,
    body: listingName('drn-106'),
    href: '/account',
    createdAt: at('09-12 07:30'),
  },
  {
    id: 'n-111',
    userId: 'demo-user',
    kind: 'rental',
    title: `レンタルが「${rentalStatusLabels.completed}」になりました`,
    body: listingName('rpl-003'),
    href: '/account',
    createdAt: at('08-25 09:10'),
    readAt: at('08-25 12:00'),
  },
  {
    id: 'n-112',
    userId: 'demo-user',
    kind: 'rental',
    title: `購入が「${orderStatusLabels.completed}」になりました`,
    body: listingName('til-104'),
    href: '/account',
    createdAt: at('08-12 16:00'),
    readAt: at('08-12 18:30'),
  },
  {
    id: 'n-113',
    userId: 'demo-admin',
    kind: 'moderation',
    title: '掲載が承認されました',
    body: listingName('til-103'),
    href: '/listings/til-103',
    createdAt: at('08-30 11:20'),
    readAt: at('08-30 11:25'),
  },
  {
    id: 'n-114',
    userId: 'demo-admin',
    kind: 'rental',
    title: `購入が「${orderStatusLabels.cancelled}」になりました`,
    body: listingName('trc-006'),
    href: '/account',
    createdAt: at('09-03 09:00'),
  },
]

const threadReads: ThreadRead[] = [
  { threadId: 's-102', userId: 'demo-seller', readAt: at('09-12 08:30') },
  { threadId: 's-112', userId: 'demo-seller', readAt: at('09-12 12:10') },
  { threadId: 's-108', userId: 'demo-seller', readAt: at('09-10 15:00') },
  { threadId: 's-105', userId: 'demo-seller', readAt: at('09-09 18:00') },
  { threadId: 's-103', userId: 'kobayashi-engei', readAt: at('09-06 18:00') },
].map((read) => ({ id: `${read.threadId}:${read.userId}`, ...read }))

const accountStatuses: AccountStatus[] = [
  {
    id: 'watanabe',
    status: 'suspended',
    note: '本人確認の書類が未提出',
    updatedAt: at('09-04 10:00'),
  },
]

type EventSeed = [DealKind, string, string, string | undefined, string, string?]

/** [kind, dealId, status, actor, when, note] — order does not matter. */
const eventSeeds: EventSeed[] = [
  [
    'order',
    'o-101',
    'requested',
    'suzuki',
    '09-13 09:40',
    '6月の内見で住環境が気に入り、購入を検討しています。',
  ],
  [
    'order',
    'o-102',
    'requested',
    'demo-user',
    '09-11 21:00',
    '入居時の引越しもこちらで相談する予定です。',
  ],
  ['order', 'o-103', 'requested', 'ito-farm', '09-09 10:00'],
  ['order', 'o-103', 'accepted', 'kobayashi-engei', '09-10 09:15'],
  ['order', 'o-104', 'requested', 'demo-user', '08-05 12:00'],
  ['order', 'o-104', 'accepted', 'demo-seller', '08-06 08:00'],
  ['order', 'o-104', 'delivered', 'demo-seller', '08-10 14:00'],
  ['order', 'o-104', 'completed', 'demo-user', '08-12 16:00'],
  ['order', 'o-105', 'requested', 'kato', '06-20 09:00'],
  ['order', 'o-105', 'accepted', 'nakamura-farm', '06-21 07:30'],
  ['order', 'o-105', 'delivered', 'nakamura-farm', '06-30 11:00'],
  ['order', 'o-105', 'completed', 'kato', '07-02 12:00'],
  [
    'order',
    'o-106',
    'requested',
    'demo-admin',
    '09-02 15:00',
    '検証用の申込です。',
  ],
  ['order', 'o-106', 'cancelled', 'demo-admin', '09-03 09:00'],
  [
    'rental',
    'r-101',
    'requested',
    'demo-user',
    '09-12 20:15',
    '2026-10-05 〜 2026-10-08',
  ],
  [
    'rental',
    'r-102',
    'requested',
    'suzuki',
    '09-01 09:30',
    '2026-09-10 〜 2026-09-16',
  ],
  ['rental', 'r-102', 'active', 'sky-agri', '09-10 08:00'],
  [
    'rental',
    'r-103',
    'requested',
    'demo-user',
    '08-10 12:00',
    '2026-08-20 〜 2026-08-24',
  ],
  ['rental', 'r-103', 'active', 'tamura', '08-20 09:00'],
  ['rental', 'r-103', 'completed', 'tamura', '08-25 09:10'],
  [
    'rental',
    'r-104',
    'requested',
    'demo-admin',
    '09-13 08:50',
    '2026-10-01 〜 2026-10-03',
  ],
  [
    'rental',
    'r-105',
    'requested',
    'ito-farm',
    '06-20 15:00',
    '2026-07-01 〜 2026-07-05',
  ],
  ['rental', 'r-105', 'active', 'demo-seller', '07-01 08:30'],
  ['rental', 'r-105', 'completed', 'demo-seller', '07-06 10:00'],
  [
    'rental',
    'r-106',
    'requested',
    'takahashi',
    '08-28 19:00',
    '2026-09-01 〜 2026-09-02',
  ],
  ['rental', 'r-106', 'cancelled', 'takahashi', '08-30 08:20'],
  [
    'rental',
    'r-107',
    'requested',
    'demo-user',
    '09-03 10:00',
    '2026-09-12 〜 2026-09-18',
  ],
  ['rental', 'r-107', 'active', 'demo-seller', '09-12 07:30'],
  [
    'rental',
    'r-108',
    'requested',
    'suzuki',
    '05-30 13:00',
    '2026-06-10 〜 2026-06-12',
  ],
  ['rental', 'r-108', 'active', 'demo-seller', '06-10 09:00'],
  ['rental', 'r-108', 'completed', 'demo-seller', '06-13 11:00'],
  ['transportJob', 'tj-101', '募集中', 'demo-seller', '09-08 09:00'],
  ['transportJob', 'tj-101', 'approved', undefined, '09-08 09:30'],
  ['transportJob', 'tj-101', '調整中', 'demo-seller', '09-09 18:00'],
  ['transportJob', 'tj-101', '運搬中', 'okada', '09-13 08:05'],
  ['transportJob', 'tj-102', '募集中', 'ito-farm', '09-05 14:00'],
  ['transportJob', 'tj-102', 'approved', undefined, '09-05 14:20'],
  ['transportJob', 'tj-102', '調整中', 'ito-farm', '09-11 17:30'],
  ['transportJob', 'tj-103', '募集中', 'kato', '09-13 07:45'],
  ['transportJob', 'tj-104', '募集中', 'nakamura-farm', '06-28 10:00'],
  ['transportJob', 'tj-104', 'approved', undefined, '06-28 10:30'],
  ['transportJob', 'tj-104', '調整中', 'nakamura-farm', '06-30 09:00'],
  ['transportJob', 'tj-104', '運搬中', 'yamamoto-transport', '07-05 08:00'],
  ['transportJob', 'tj-104', '完了', 'nakamura-farm', '07-05 15:40'],
]

const dealEvents: DealEvent[] = eventSeeds
  .map(([dealKind, dealId, status, actorUserId, when, note], index) => ({
    id: `ev-${String(index + 101)}`,
    dealKind,
    dealId,
    status,
    actorUserId,
    note,
    createdAt: at(when),
  }))
  .sort((a, b) => b.createdAt.localeCompare(a.createdAt))

export const demoActivity: DemoActivity = {
  listings,
  transportJobs,
  submissions,
  messages,
  rentals,
  orders,
  reviews,
  carrierProfiles,
  notifications,
  threadReads,
  accountStatuses,
  dealEvents,
}
